name: ETA noVNC
version: "1.0.2"
slug: eta_novnc
description: noVNC Webinterface für eine ETA ETAtouch VNC-Verbindung

arch:
  - aarch64

startup: application
boot: auto
init: false

ingress: true
ingress_port: 6080
panel_icon: mdi:fire
panel_title: ETA ETAtouch

options:
  vnc_host: "192.168.2.160"
  vnc_port: 5900
  vnc_password: ""

schema:
  vnc_host: str
  vnc_port: int
  vnc_password: password